local colors = require("config.rusty-scheme")
vim.cmd.colorscheme("bluloco")

vim.api.nvim_set_hl(0, "Normal", { bg = colors.darkest_blue, fg = colors.off_white })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = colors.float_bg, fg = colors.off_white })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = colors.float_bg, fg = colors.light_yellow })
vim.api.nvim_set_hl(0, "NvimFloat", { bg = colors.float_bg, fg = colors.off_white })
vim.api.nvim_set_hl(0, "FloatTitle", { bg = colors.float_bg, fg = colors.off_white })
vim.api.nvim_set_hl(0, "FloatShadow", { bg = colors.float_bg, fg = colors.off_white })
vim.api.nvim_set_hl(0, "FloatShadowThrough", { bg = colors.float_bg, fg = colors.off_white })
vim.api.nvim_set_hl(0, "LineNr", { fg = colors.dark_gray })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = colors.yellow, bold = true })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "none" })
vim.api.nvim_set_hl(0, "Number", { fg = colors.dark_blue })
vim.api.nvim_set_hl(0, "String", { fg = colors.dark_blue })
vim.api.nvim_set_hl(0, "Comment", { fg = colors.dark_gray })
vim.api.nvim_set_hl(0, "Pmenu", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "PmenuSBar", { fg = colors.gray, bg = colors.gray })
vim.api.nvim_set_hl(0, "PmenuThumb", { fg = colors.dark_gray, bg = colors.dark_gray })
vim.api.nvim_set_hl(0, "MsgArea", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "NormalNC", { link = "Normal" })

vim.api.nvim_set_hl(0, "DarkBlue", {  fg = colors.dark_blue })
vim.api.nvim_set_hl(0, "DarkBlueBold", {  fg = colors.dark_blue, bold = true })
vim.api.nvim_set_hl(0, "DarkGreen", {  fg = colors.dark_green  })
vim.api.nvim_set_hl(0, "DarkOrange", {  fg = colors.dark_orange })
vim.api.nvim_set_hl(0, "DarkOrangeUnderline", {  fg = colors.dark_orange, underline = true })
vim.api.nvim_set_hl(0, "DarkPurple", {  fg = colors.dark_purple })
vim.api.nvim_set_hl(0, "Gray", {  fg = colors.gray })
vim.api.nvim_set_hl(0, "LightBlue", {  fg = colors.light_blue })
vim.api.nvim_set_hl(0, "LightBlueItalic", {  fg = colors.light_blue, italic = true })
vim.api.nvim_set_hl(0, "LightGray", {  fg = colors.light_gray })
vim.api.nvim_set_hl(0, "LightGreenBold", {  bold = true, fg = colors.light_green })
vim.api.nvim_set_hl(0, "LightOrangeUnderline", {  fg = colors.light_orange, underline = true })
vim.api.nvim_set_hl(0, "LightRedItalic", { fg = colors.light_red, italic = true })
vim.api.nvim_set_hl(0, "LightRedUnderline", { fg = colors.light_red, underline = true })
vim.api.nvim_set_hl(0, "LightYellow", {  fg = colors.light_yellow })
vim.api.nvim_set_hl(0, "LightYellowItalic", {  fg = colors.light_yellow, italic = true })
vim.api.nvim_set_hl(0, "Orange", {  fg = colors.dark_orange })
vim.api.nvim_set_hl(0, "Pale", {  fg = colors.pale })
vim.api.nvim_set_hl(0, "PaleUnderline", {  fg = colors.pale, underline = true })
vim.api.nvim_set_hl(0, "Purple", {  fg = colors.purple })
vim.api.nvim_set_hl(0, "Teal", {  fg = colors.teal })
vim.api.nvim_set_hl(0, "Yellow", {  fg = colors.yellow })

-- RUBY
vim.api.nvim_set_hl(0, "rubyBoolean", { link = "LightRedItalic" })
vim.api.nvim_set_hl(0, "rubyClass", { link = "LightOrangeUnderline" })
vim.api.nvim_set_hl(0, "rubyModule", { link = "LightOrangeUnderline" })
vim.api.nvim_set_hl(0, "rubyConstant", { link = "DarkGreen" })
vim.api.nvim_set_hl(0, "@lsp.type.namespace", { link = "DarkGreen" })
vim.api.nvim_set_hl(0, "rubyInstanceVariable", { link = "Purple" })
vim.api.nvim_set_hl(0, "rubySymbol", { link = "Teal" })
vim.api.nvim_set_hl(0, "rubyCurlyBlockDelimiter", { link = "Normal" })
vim.api.nvim_set_hl(0, "rubyConditional", { link = "LightRedUnderline" })
vim.api.nvim_set_hl(0, "rubyControl", { link = "DarkOrange" })
vim.api.nvim_set_hl(0, "rubyFunction", { link = "LightBlue" })
vim.api.nvim_set_hl(0, "rubyDefine", { link = "DarkBlue" })
vim.api.nvim_set_hl(0, "rubyException", { link = "DarkOrangeUnderline" })
vim.api.nvim_set_hl(0, "rubyInterpolation", { link = "PaleUnderline" })
vim.api.nvim_set_hl(0, "rubyInterpolationDelimiter", { link = "Pale" })
vim.api.nvim_set_hl(0, "rubyPseudoVariable", { link = "Purple" })
vim.api.nvim_set_hl(0, "rubyMacro", { link = "LightBlueItalic" })
vim.api.nvim_set_hl(0, "rubyString", { link = "DarkBlue" })
vim.api.nvim_set_hl(0, "rubyCallback", { link = "LightYellowItalic" })
vim.api.nvim_set_hl(0, "rubyValidation", { link = "LightYellowItalic" })
vim.api.nvim_set_hl(0, "rubyEntities", { link = "LightYellowItalic" })
vim.api.nvim_set_hl(0, "rubyEntity", { link = "LightYellowItalic" })
vim.api.nvim_set_hl(0, "rubyKeyword", { link = "Yellow" })
vim.api.nvim_set_hl(0, "rubyBlockParameter", { link = "Orange" })
vim.api.nvim_set_hl(0, "rubyBlockParameterList", { link = "Orange" })

vim.api.nvim_set_hl(0, "@lsp.type.variable.ruby", { })
vim.api.nvim_set_hl(0, "@lsp.type.method.ruby", { })
vim.api.nvim_set_hl(0, "@lsp.type.parameter.ruby", { })

-- Selection
vim.api.nvim_set_hl(0, "CmpSelect", { fg = colors.teal, bg = colors.dark_gray })
-- Match part of text
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = colors.light_orange, bold = true })
